### ISSUE TITLE
fix: add ensureVisible  before actions to ensure the elements are not off the screen

### ISSUE THREAD

**Issue by flavio-silva** [wolfenrain/fluttium#103] opened 2022-10-28 20:01 UTC
If a page is bigger than the device screen the tests can't hit (tapOn, expectVisible) some widgets that are off the screen.

For example a large form that needs to be down scrolled in order to click on "Save" button

**Comment by wolfenrain** [comment] 2022-11-01 13:55
I am not entirely sure what the problem is here, a normal user wouldn't be able to tap on items that are off screen either.

If you are looking for the ability to scroll then #4 will add that support once it lands

**Comment by wolfenrain** [comment] 2023-03-11 16:02
Closing this as it will be solved as part of #4.

**Closed by wolfenrain** 2023-03-11 16:02 UTC
Labels: bug
