### ISSUE TITLE
docs: Following the installation guide results in error on Hello World log. 

### ISSUE THREAD

**Issue by danielroek** [wolfenrain/fluttium#306] opened 2023-07-16 17:24 UTC
**Description**

Not really sure what the improvement should be, as I have not yet solved the issue. But when following the guide on fluttium.dev, the first teste results in the following output:
```
  My first Fluttium flow.


 Fatal driver exception occurred: Invalid argument (name): An action with this name is not registered.: "log"
✓ Uninstalling test runner (1.4s)
```

I've tried to use the git-hosted log_action, but that did not help either. 

**Requirements**

- [ ] Update documentation so the setup works on the first try.

**Comment by wolfenrain** [comment] 2023-07-16 17:35
Thanks for opening up an issue! Can you provide your Fluttium.yaml? I suspect either the path is wrong there or registering isn't working as intended (tho it should as with any bug haha)

**Comment by danielroek** [comment] 2023-07-16 17:44
My fluttium.yaml is the default one that is generated by `fluttium init`:

```yaml
# The following defines the environment for your Fluttium project. It includes 
# the version of Fluttium that the project requires.
environment:
  fluttium: ">=0.1.0 <1.0.0"

# The driver can be configured with default values. Uncomment the following 
# lines to automatically run Fluttium using a different flavor and dart-defines.
  driver:
    target: lib/main_development.dart
    flavor: development
#   dart_defines:
#     - CUSTOM_DART_DEFINE=1

# Register actions which can be used within your Fluttium flows.
actions:
  # The following adds the log action to your project.
  log_action: 0.2.0
```

**Comment by danielroek** [comment] 2023-07-16 17:49
Found what the problem is. I initialized the file in the test folder. Moved it up one level, to be in the project root and now it works :) 

The documentation states the following: 
```
Once fluttium_cli is installed, we can use the init command to initialize Fluttium in the current project. This command will generate a fluttium.yaml in the current directory. This allows you to install custom actions and configure the Fluttium driver.
```

But that doesn't really reflect that it should be initialized in the project root.

**Comment by danielroek** [comment] 2023-07-16 17:52
This issue can also be converted to a feature request that `fluttium.yaml` should support calling the target with `../some_folder/entry_point.dart`

**Comment by wolfenrain** [comment] 2023-07-19 13:53
The idea of the `fluttium.yaml` is that it will always live in the root of a Flutter project (this can be more specific in the docs 😉) so it able to perfectly figure out all the paths as any flutter command normally would. 

Glad to know that you found the problem with the issue tho! 

I'll close this issue for now, but if you strongly feel that Fluttium should support a way to specify a working directory in the config then please do open a new issue so we can discuss that further there ❤️

**Closed by wolfenrain** 2023-07-19 13:53 UTC
Labels: documentation
